<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260729132837 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, score INT NOT NULL, created_at DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE guess (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, country VARCHAR(255) NOT NULL, distance_km INT NOT NULL, score INT NOT NULL, round_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_32D30F96A6005CA0 ON guess (round_id)');
        $this->addSql('CREATE TABLE round (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, image_url VARCHAR(255) NOT NULL, correct_country VARCHAR(255) NOT NULL, guessed_country VARCHAR(255) DEFAULT NULL, is_correct BOOLEAN NOT NULL, game_id INT DEFAULT NULL, guess_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C5EEEA34E48FD905 ON round (game_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C5EEEA3479D9EE1 ON round (guess_id)');
        $this->addSql('ALTER TABLE guess ADD CONSTRAINT FK_32D30F96A6005CA0 FOREIGN KEY (round_id) REFERENCES round (id)');
        $this->addSql('ALTER TABLE round ADD CONSTRAINT FK_C5EEEA34E48FD905 FOREIGN KEY (game_id) REFERENCES game (id)');
        $this->addSql('ALTER TABLE round ADD CONSTRAINT FK_C5EEEA3479D9EE1 FOREIGN KEY (guess_id) REFERENCES guess (id)');
        $this->addSql('ALTER TABLE player ADD score INT NOT NULL');
        $this->addSql('ALTER TABLE player ALTER image_url DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE guess DROP CONSTRAINT FK_32D30F96A6005CA0');
        $this->addSql('ALTER TABLE round DROP CONSTRAINT FK_C5EEEA34E48FD905');
        $this->addSql('ALTER TABLE round DROP CONSTRAINT FK_C5EEEA3479D9EE1');
        $this->addSql('DROP TABLE game');
        $this->addSql('DROP TABLE guess');
        $this->addSql('DROP TABLE round');
        $this->addSql('ALTER TABLE player DROP score');
        $this->addSql('ALTER TABLE player ALTER image_url SET NOT NULL');
    }
}
